name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Backend
      run: docker build -t backend ./backend

    - name: Run Tests
      run: docker run backend pytest || true

    - name: Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: backend

    - name: Login DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Images
      run: |
        docker tag backend yekabotesomashekhar11/backend:latest
        docker push yekabotesomashekhar11/backend:latest
